### ISSUE TITLE
town skins (custom icons) for wild_info.txt (world map)

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#137]
atm `# Town symbols should match locations in town.txt.`

It means that I have to make all my locations as 'town' (as all of them are towns) on map and it looks really stupid if you push ^W :D

/rfe
Add an option to assign decorative tile-skin for town (skins will link `name:` field from `terrain.txt`)

so `wild_info.txt` will have "config" in header, eg:
`<town flag>:<skin symbol>:<name from terrain.txt>` , eg:

feat:T:1:obj_grass j wagon
feat:T:2:obj_grass d gravestone
feat:T:3:obj_grass c sealed portal
feat:T:4:obj_grass 5 skulls pile
feat:T:5:flower D red
...

So if now I've got map like this:
TTTTTT
TTTTTT
TTTTTT

With this feature it will be something like:
a17eb9
z9y495
19i8co

**Comment by draconisPW** [comment]
Done. Define your desired feature in terrain.txt (take name:town as example), tile mapping in graf-xxx.prf and add the "symbol:feature name" line in town.txt with feature name = the name of the feature you defined in terrain.txt.

For PWMAngband, The Brandywine Bridge is now defined as "symbol:drawbridge" to show a "bridge" instead of a "town" picture.
