### ISSUE TITLE
'space' in race name prevent it's appearance

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#172]
races:
```
Black Numenorean
Black Dwarf
Forest Goblin
```

showed as default tiles, while all other races (which don't have ' ' - space in name) - showed properly

**Comment by draconisPW** [comment]
Nice catch. Also when the race name is too long, it leaves a trail on the birth screen -- solution: truncate the name (best would be to stick to shorter names).

**Comment by draconisPW** [comment]
Fixed.

Since it's impossible to rewrite the whole file parser, I've made a workaround: in xtra-xxx.prf, when a race has a space in it, replace that space by an underscore. For example:

?:[AND [EQU $CLASS Warrior] [EQU $RACE Black_Numenorean] ]

The parser will recognize that underscore and replace it with a space.
