### ISSUE TITLE
Taking a one item from the ground from pile

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#203]
when you want to take one item from the ground from a pile - you take all of them instead taking only one.

repro:
1) drop 2 different items on the ground to form a pile
2) use pick up command
3) game will promt which item to pick up
4) you choose 1 item.. but you will pick up all two items

**Comment by draconisPW** [comment]
Probably a consequence on a change in V which makes all items dropped by the player drop at the same location.

**Comment by draconisPW** [comment]
Strangely I can't reproduce this with the admin although I'm sure to have seen this already.

**Comment by igroglaz** [comment]
Yep, admin doesn't have this problem. But my 'player' character just tested it - drop 2 different scrolls on the ground. When I pickup one - two picked up

**Comment by draconisPW** [comment]
Hmm I can't reproduce. But for me, when I try to pick up a pile of items, the first and last items work fine, but the middle items take two presses of key to pick up. Strange...

**Comment by draconisPW** [comment]
Picking up first item is fine. Picking up following items has a call to "redraw floor" in between, which doesn't set objects in the same order, that's why the pickup function on the client asks twice (it considers that the floor has changed and re-ask to be sure you don't pick up the wrong item). Picking up the last item is also fine since there is only one item in the list and therefore cannot change.

**Comment by draconisPW** [comment]
Server sends 2 packets: redraw floor + ask for item to pick up. First packet is way bigger than the second, so it may take more time to transport and arrive on client AFTER the demand for request, which of course cannot work since it would work on an outdated version of the floor (if we want to pick up items, we need to remind the client that we already picked items up). I need to ensure that the two packets arrive on client in the proper order.

The only reason the client should ask again is the case where the pile under @ has been altered and it receives a floor update while the player is choosing an item to pick up. For example, player has dropped two scrolls and wants to pick them up and brings the list, but in the meantime a fire hound has come, breathed fire on the @ and destroyed the scroll on the floor, which then wouldn't be there to pick up anymore...

**Comment by draconisPW** [comment]
This SEEMS fixed :)

**Comment by draconisPW** [comment]
I just downloaded Tangaria /lib and the initial bug (picking up everything in a pile) is not fixed :(

**Comment by draconisPW** [comment]
Oh ok I got it now, it's because the "quick_floor" option is bugged: it just checks if there is only one item REMAINING on the floor to pick it up, so you will have a menu until there are 2 items and then the last 2 are picked up simultaneously. I was not using that option so it was fine with me. Fix: only apply "quick_floor" if there is one item in the pile.

**Comment by draconisPW** [comment]
Now it's fixed :)
