### ISSUE TITLE
login with another player character

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#226]
there is a glitch - when player could login with another player character

**Comment by draconisPW** [comment]
I'll try to reproduce this but since I've never seen such glitch I guess it will be hard...

**Comment by draconisPW** [comment]
It's not a glitch, it's a critical security bug.

1) Create account A with password A + character A
2) Create account B with password B + character B
3) Wipe the server file
4) Player B connects to his account B which has no more chars
5) Player B enters "A" and recreates bogus char A
6) Player B gets access to the real char A
7) Player B leaves, char A gets bound to account B
8) Player A connects to his account A which has no more chars
9) Player A enters "A", char creation is denied with "Invalid account" error

The problem is: at step 9, password is checked; at step 5, password is NOT checked. This allows player B to hack player A's account and take control of his character.

**Comment by draconisPW** [comment]
The main problem is having the player list saved in the server savefile while it clearly should not.

**Comment by draconisPW** [comment]
- save player id counter + player names in a separate file
- when loading player savefile, GET THE PASSWORD and compare with the provided password, THE TWO MUST MATCH!

**Comment by igroglaz** [comment]
Does MAng also got this trouble? @flambard-took

**Comment by draconisPW** [comment]
Implemented in next beta.

**Comment by draconisPW** [comment]
When playing around with my dev version, I've managed to connect with the admin account and see 3x the admin char on the list of characters. There is definitely a bug there.

**Comment by draconisPW** [comment]
Got it! Some characters are generated with the same id. So looking for a character or saving player names can't work, they require distinct ids. I need to add a "repair" feature to ensure that all ids are distinct.

**Comment by draconisPW** [comment]
In fact, this only happens when the server was wiped and player_id was reset. When trying to connect with an existing character, we load the character with the id saved in the character savefile which is now meaningless since we restarted from 1 so we may end up with duplicates. We need to add a check to see if id is already used and in this case increment and use player_id instead.

**Comment by draconisPW** [comment]
- remove duplicates from the player name database in rd_player_names()
- use new player id if player id already exists in the player name database when loading player savefile

**Comment by draconisPW** [comment]
Finally fixed in next beta.

**Comment by igroglaz** [comment]
Apparently it's not fixed. I've logged in my account and found there character 'Lexx' while instead of mine.. I've sent save folder in discord PM

**Comment by draconisPW** [comment]
Reinvestigating with the save folder given.

**Comment by draconisPW** [comment]
In the save folder, there is no "Tangar" character. When I connect to the "Tangar" account, I see no character on the list so I use the character creation screen to make the character load again. This works fine. This means the problem occured before player file was saved.

Problem: id of the Tangar character is 22, which is the same as character Lexx. Character "Lexx" should never had been generated with id 22. The problem then happened for character Lexx, not Tangar.

Examining the logs on 13/08:

130820 085311 Welcome Lexx=Lexxart@MyTrend (95.188.88.114) (version 1410)
130820 085354 Unknown packet type Lexx (058,01)
130820 085354 Goodbye Lexx=Lexxart@MyTrend ("Unknown packet type")
130820 085401 Welcome Lexx=Lexxart@MyTrend (95.188.88.114) (version 1410)
130820 085512 Player Name is [Lexx], id is 22

See that "Unknown packet" message? This is probably the reason why the character was created, but with the wrong id.

**Comment by draconisPW** [comment]
This is really weird... I don't see how a character could be created with the previous' char id... If the packet error occurs too soon the id will be 0 so next time it will be set to max id + 1, and if the packet error occurs too late the id will already be set to max id +1...

**Comment by igroglaz** [comment]
maybe if chars got deleted - IDs moves?

**Comment by draconisPW** [comment]
In all cases I just added some extra check when player connects.

130820 085512 Player Name is [Lexx], id is 22

In this case, if id = 22 already exists, I simply reassign the id to a new one, this should ensure the problem doesn't happen again.
