### ISSUE TITLE
game was blocked by Windows 7 firewall just in the middle of the gameplay

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#232]
Today suddenly my Windows 7 firewall blocked client without any reason to do it, just in the middle of the game. I've got several error messages (on client side only) which you could see at my stream (turn on 0.25 video speed to catch all of them):
**https://youtu.be/iJ9u-gu5IHY?t=2912**

server logs:

```
170720 120629 Tangar: You hit the kobold shaman.
170720 120629 Tangar: You have slain the kobold shaman.
170720 120630 Tangar: The small kobold wakes up.
170720 120631 Tangar: The small kobold misses you.
170720 120631 Tangar: You hit the small kobold.
170720 120631 Tangar: You have slain the small kobold.
170720 120651 Disconnected from server...
170720 120654 Goodbye Tangar=nick@hp ("Client quit")
```

Problem gone after I've added game client to Windows firewall (added .exe file to 'allowed').

Before that I've played several hours with that setup.. And also played for years at that particular notebook. So it's pretty strange behaviour.

**Comment by draconisPW** [comment]
Well not much I can do with your Windows configuration...

I remember when I had Windows 7 I could play normally and register my local server on the meta. Now with Windows 10 I can't do this anymore, even if I declare mangband.exe to the firewall and open the corresponding ports it still gets blocked for whatever reason.

I also have a problem when downloading Vanilla Angband on my laptop: each time I run the game, I get "WS.Reputation.1" alert because the file has low dowloading from the website and it's not trusted.

Anyway, nothing I can do here, you have to fix that with your antivirus/firewall configuration.

**Comment by igroglaz** [comment]
Yep, I've fixed it already as I wrote in 1st message. But the point is - that this problem appeared just now suddenly, while before it didn't appear. So maybe it's connected with some recent PWMA updates?

**Comment by draconisPW** [comment]
It has nothing to do with the game. What happened during your stream is a network slowdown (the "time out" messages) leading to the client being disconnected because of unresponsiveness (error messges because the disconnection happened in the middle of a network check so it didn't leave cleanly).

**Comment by igroglaz** [comment]
Yep.. But it happened cause Windows firewall blocked the client. As right after this I failed to login with different variations of clients/accounts... Only after I've added it to exclusions - game started workign immideately.. Anyway, I just wanted to report this case to you, so you will know about it, just in case
