### ISSUE TITLE
[bug] monsters do not dissapear / target dummy not visible

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#240]
it seems monsters in town stack.. and also target dummy doesn't show in it's place. It shows that its somewhere (see screenshot), but I can't find it.
https://snipboard.io/SzNrQ5.jpg

I've tried to go to another location and wait there 24 hours (admin menu &->8), mobs didn't reset

maybe new system (mobs do not dissapear if player around) glitches?

**Comment by draconisPW** [comment]
Target dummy not at its place is my fault... I used Teleport Other on it with my Sorceror 🤣. He'll be repositioned next time the townie list is wiped.

For townies, they only reset when the number of townies reach the maximum number set in the town file. By default, max number is 100. If they don't reset, it's because you have set -1 (no maximum) in the town file. In the past day, I've constantly mass banished the town with my sorceror to keep the value low because it's a nightmare to wander around town. Please consider putting a limit back to the max number.
