### ISSUE TITLE
item prices in player's stores

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#243]
right now prices in player's stores based on NPC prices which brings troubles, eg

 I've got 0 price for food rations as I don't want them to appear in NPC stores
```
name:& Ration~ of Food
graphics:,:U
type:food
level:1
weight:8
cost:0
alloc:20:1 to 50
pile:100:1d2
effect:NOURISH:INC_BY
dice:40
msg_self:That tastes good.
desc:This nutritious but fairly bland food is familiar to anyone contemplating
desc: long journeys.
```

if player put 'for sale 1000' - price still will be N/A

--

/rfe sell stuff in players stores at the price assigned by player

**Comment by draconisPW** [comment]
The easiest way to fix this is to assign a low value (for example: 1) instead of 0. The item will never appear in NPC store unless it is explicitely declared in store.txt and any value below 10 will prevent the item from being generated in black markets. Items that are not useless should NEVER have a value of 0.

**Comment by igroglaz** [comment]
It won't help. Eg if I assign Ration of Food for 1-10 gold (so it won't appear in Black Market) - the price in player store will be 10 gold. While player wants to sell it for 800 gold.

/rfe sell stuff in players stores at the price assigned by player

**Comment by draconisPW** [comment]
I see. Currently the price you can put is capped at 2x the XBM, so for an item with price = 1, the maximum price you can set is 40. I can probably remove that restriction, since you could always put a ration for sale 1 million, but nobody would ever buy it.

**Comment by draconisPW** [comment]
I'll change this when I'm back from holidays.

**Comment by draconisPW** [comment]
Just a thought before I forget it: I could add the "preferred price" on an item when it is for sale, so people could see if they're getting scammed -- the price that is currently set (2x the XBM price). So instead of a strict cap, I remove the cap and just list is as "preferred price" when examining the item in player shops.

**Comment by igroglaz** [comment]
I don't think anyone will try to scam in our niche, tiny and friendly community. No need to complicate the system. Just remove restriction.

**Comment by igroglaz** [comment]
ezpz way to fix (how I did @ T server code):

comment out in store.c /* Player owned shops */:
```
    /* Worthless items */
    if (price <= 0) return (0L);
```

and
`    if (price > maxprice) price = maxprice;`

**Comment by igroglaz** [comment]
yet another stupid restriction is 

```
        /* Can't sell unindentified items */
        if (!object_is_known(p, obj))
        {
            msg(p, "You must identify this item first.");
            return;
        }
```

As a lot of (new) players don't have plenty ID scrolls, why they can't sell stuff.. Roguelike = freedom. There are no need of such restrictions, they just make game less fun.

**Comment by draconisPW** [comment]
- remove 2x XBM price restriction when selling items in player shops
- add preferred price (BM price) when inspecting object
- use "askprice" for worthless items (unless said askprice is set to 0 -- in which case item is just for "show off") when selling items in player shops

Restriction on unID items cannot be lifted because it will screw up price calculation. If you comment out that part, be prepared to face severe pricing bugs. Items sold in stores, whereas they are normal or player stores, have to be identified.

**Comment by igroglaz** [comment]
We only need to allow selling unID items in player's stores. So new player will have possibility to trade easier. It's very often when new players got a lot of items, but don't have scrolls to ID them. Selling them to another players could be good idea
