### ISSUE TITLE
server option: do not show level treasure feeling

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#247]
/rfe add option to server cfg to hide treasure level feeling.

I've noticed that it's one of things which gives to the game 'artificial' flavour and make is more grindy. Players shouldn't know is there +9 speed ring on the lvl or not - just play and have surprises during your adventure.

**Comment by draconisPW** [comment]
Hmm I don't like hiding things much, but that's a birth option and there are already many birth options implemented as server options so why not. Derakon is a known Angband player who actually hates the level feelings and simply always play without because he thinks level feelings are dumb. I can understand that.

**Comment by igroglaz** [comment]
applied fast&dirty fix to it by returning 0 in all cases for 
**generate.c**
`static int calc_obj_feeling(struct chunk *c)`

**Comment by draconisPW** [comment]
Change from boolean (birth_feelings) to integer with 0 = none, 1 = only display level danger, 2 = display level + object feelings.

**Comment by igroglaz** [comment]
Birth options are client based, so some players will use this advantage, while others not. Better make it cfg server option to put all players in equal roguelikish condition :)

**Comment by draconisPW** [comment]
Server option LEVEL_FEELINGS added with 0 = none, 1 = only display level feeling after some exploration, 2 = always display level feeling + display object feeling after some exploration (default).

Note: I've found a bug while doing this. Feeling is not triggered if a player enters a level with another player on it, because the feeling squares are only set for the player that generates the level.

**Comment by draconisPW** [comment]
Bug fixed.
