### ISSUE TITLE
Input key queue flushed too soon

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#253]
Demo: https://youtu.be/1z8wVnSubis

In **Windows 10** SDL client doesn't react on keys sometimes. I thought it was cause my keyboard. But even after I've changed - problem exist. But in regular (mangclient.exe) - there is no such problem, it's only in SDL...

**Comment by igroglaz** [comment]
Demo #2:
https://youtu.be/9ub_4cy8Gjg

**Comment by draconisPW** [comment]
Reproduced locally. Use '.' and direction to run an repeat, after a while the '.' won't be registered. So theoretically this could happen with any key.

**Comment by draconisPW** [comment]
sdl_keypress() properly calls Term_keypress(), but the key is not processed... I'm puzzled...

**Comment by draconisPW** [comment]
Ok this has nothing to do with the SDL client, that's why I didn't understand. During the main loop, the game processes the input keys and then calls the "flush" method asynchronously to reset the "head" of the pile so that the number doesn't increment indefinitely. With the Win client, processing the input queue takes less time than with the SDL client so the "flush" method is always called afterwards. With SDL client, the "flush" method may be called too soon, clearing the input queue before the keys have been all processed.

Fixing this will be tricky...

**Comment by draconisPW** [comment]
Implemented a horrible hack to fix this. I hope it doesn't break anything else...
