### ISSUE TITLE
Challenging level server option

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#264]
/rfe make optional (constants.txt?):

**src/server/gen-cave.c**
```
/* PWMAngband: don't convert pit walls */
            if (square_isrock(c, &change) && !square_ispermfake(c, &change))
```

We shouldn't reduce variability of game situations. It is quite rare chance for streamer to pass pit - and when it does it's beautiful and roguelikish thing.

I think we could disable this for end-game dungeons (cause there are too harsh mobs) while in early and mid-game it should stay... 

Also maybe add there certain probability to convert pit wall depending on depth.. so the deeper you go - the less chance to convert wall there will be.. so for early game it's 1, mid-game 1/3, end-game 1/10

---

Also considering past change: `Don't customize pit/vault walls with passable or projectable terrain`.
I agree with vaults, they should be closed.. but pits walls are alright to be passable IF there were pierced by streamer as it's quite extraordinary case (explanation is written above).

**Comment by draconisPW** [comment]
Sorry but this won't happen, even if it would make better customization, because it would simply break the "surprise" of the pit feature. I already updated pits so that no monsters can escape except from the front door. It was retarded to have G pits and see those passwall ghosts simply leave the area. Now walls are permanent, only the entrance door can be used to escape or enter. And floor is NO_TELEPORT, makes monsters also not leave the pit via teleport... as well, of course, as make entering dangerous for the player.

Pits should be unbreakable and even unpredictable. I am ALMOST tempted to make them un-detectable, so you won't know what's inside until you open the door. Having that big opaque room, casting Detect Monsters and seeing that is a jelly pit, or an eye pit, or... nothing, is underwhelming.

**Comment by igroglaz** [comment]
1) Pits do not have any surprize. When experienced player see the pit room with it's square wall and corridor outside - he is in 95% times could say - ok, this is a pit. No surprize there. So.. if at least some of pits will be modified by streamers - it will make game much more diverse and less boring.
2) "no monsters can escape except from the front door" - this makes dungeon _artificial_, not roguelikish.

Please could you add such option for constants.txt or server.cfg. Other way I had to comment out it in the server code which is not convenient, as I'll have to do it manually after every update.

**Comment by igroglaz** [comment]
I've reverted to previous state:

```
            /* Only convert walls */
            if (square_isrock(c, &change))
            {
                /* Turn the rock into the vein type */
                square_set_feat(c, &change, feat);

                /* Sometimes add known treasure */
                if (one_in_(chance)) square_upgrade_mineral(c, &change);
            }
```

Lets make it really cool by adding there similar stuff like in https://github.com/draconisPW/PWMAngband/issues/248 ... use (randint0(wpos->depth) to reduce numbers of pit wall convertations with depth. It will be really fun! :bear:

**Comment by draconisPW** [comment]
Add CHALLENGING_LEVELS server option for more challenging levels. Above stuff will fill in this, as well as other ideas that may come out.

**Comment by draconisPW** [comment]
Option implemented. For now, it is just used to allow streamers to cross pits with probability depending on depth (less chance the deeper). This could be enriched later with more stuff.

**Comment by igroglaz** [comment]
AWESOME.
