### ISSUE TITLE
check artifacts allocation

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#279]
```
[23:31] PowerWyrm: 
alloc on artifact is not used since it's recalculated anyway, so the ones with positive are simply the ones from V where I didn't remove the value
------------------------

[21:25] PowerWyrm: need to check that (I thhought it was only for randarts)
```

**Comment by draconisPW** [comment]
I checked and found the following in alloc_init_objects():
- if an artifact has an allocation value (allocation probability on line "alloc: allocation probability : min depth : max depth" in artifact.txt), this value is used
- if an artifact doesn't have an allocation value (allocation probability = 0 in artifact.txt), it is calculated proportionnally to the artifact's value

All PWMAngband artifacts have no allocation probability (since I didn't know what to set for it), so it's automatically calculated. All regular Angband artifacts have classic allocation probability, so they use that value.
