### ISSUE TITLE
gauntlet levels -> 50% scramble to teleport

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#300]
atm there are levels which completely block teleport on them which is too bad... especially to certain classes. as you've become trapped there. this level type may be considered better is actual effect on them will be less cruel - eg 50 (or even 25%) chance to fizzle teleport attempt.

also it will be fun to make it RISK vs REWARD - so even though it will have 25-50% teleport fail - such levels will contain garanteed 6-10 level treasure feeling.. so players will consider to explore them instead just skipping

**Comment by draconisPW** [comment]
I would consider making the left part "limited teleportation" (aka allow phase door) instead of "no teleport" just to keep the design valid (using teleport to get to the "safe" part would break the purpose of the level). At low level you can probably clear the hard part, and at high level you have other ways to deal with the problem (earthquake, destruction, banishment...).

Concerning level feeling, the design adds a labyrinth in the middle which is packed with treasures, so the feeling should always be high. It's either leave or risk entering it.

**Comment by draconisPW** [comment]
NO_TELEPORT changed to LIMITED_TELE which allows phase door to work.
