### ISSUE TITLE
confusing order of messages after switching items

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#308]
when you switch items with ctrl+x or w0-9 game writes message window messages in not comfortable order... first it writes which item you wear now and next which you were wearing which is very confusing.

eg

I switch item 1 to item 2 and got message:

You are wearing item 1.
You were wearing item 2.

it should be

You were wearing item 2.
You are wearing item 1.

it's confusing as when you switch items - it's hard to remember which item do you have now. So the easiest way to understand it fast - to see the last message.

**Comment by draconisPW** [comment]
I can't swap the messages because 1) there can be more in inven_wield() due to curses, pack combining/reordering/overflow and 2) the equip slot is only calculated after the switch and would be incorrect. Only thing I can do is repeat the message at the end so you would get:
- you are wielding x
- messages related to wielding x
- you were wielding y
- you are wielding x (repeated)

**Comment by draconisPW** [comment]
Implemented.
