### ISSUE TITLE
[HP] flag

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#316]
/rfe add [HP] or [LIFE] flag which will work similary like [MANA] - give certain % of hitpoints. Will be useful to rebalance certain races/classes/equip (not only with +life, but also with -life property)

**Comment by draconisPW** [comment]
Very powerful flag, as for now HP pool is balanced towards V setup and having +hp in the end would probably make the game way too easy. I'll keep that for future reference.

**Comment by igroglaz** [comment]
Yep. it's powerful.. but we will use it not only to +, but also to - :D imagine some OP races or artifacts where you pay some amount of HPs for extraordinary powers.

For now I wanna give pixie +HP at lvl 20 till ~35 so it will survive without mana shield

**Comment by draconisPW** [comment]
I have a problem with LIFE flag: if we give it to Pixie to boost classes like Mage it is fine because you will just give 10 hps at level 20 (50 -> 60); but let's say I want to play a Pixie Warrior (4+10= hit rate of 14, which is the same as a Human Archer) I would get 30 more hps (150 -> 180) to a build that really doesn't need it. Plus if you add it on items, you could use it on Ent Warriors to get an absurd amount of hps.

That's why I can't do anything right now, I need to think of a system before that would for example only boost race HD and cap the boost somehow.

**Comment by igroglaz** [comment]
yes! that's why we need add limitation to certain race-class combos: https://github.com/draconisPW/PWMAngband/issues/5

**Comment by igroglaz** [comment]
damm closed it accidentally
