### ISSUE TITLE
do not overwrite dumps on server

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#327]
atm dumps after char death has such file format <char_name>.txt .. they are stored in lib\user\scores

/rfe make file format at <char-name_date>.txt

then dumps will be stored on server without replacement.. eg atm I've lost one of pretty good dumps cause I've overwritten it on oook (forgot to 'protect')

**Comment by draconisPW** [comment]
The server dumps already are like that (MAngband feature). They are just not generated if character level is lower than 20. Maybe remove that restriction?

**Comment by igroglaz** [comment]
It would be awesome :D as getting 20 lvl by some race/class combo could be quite big achievement :)

**Comment by draconisPW** [comment]
The "server" dumps are stored in /user not in /user/scores by the way. If lower than level 20, the dump is simply something like:

# 0|179|03/29/21|Toto|f| 0| 0|  1|  0|  1|  0|drowning|1.5.0

It's the dump that is used on the MAngband ladder, but since we don't have a ladder maybe simply remove this an make a normal dump.

**Comment by draconisPW** [comment]
Ladder info has been removed and server dump always generated. So you have:
- /user/score/char.txt for client dump
- /user/char-date.txt for server dump

**Comment by igroglaz** [comment]
Please is it possible to leave ladder info too? Cause I suppose one day I'll add ladder and server statistics to the website :)
