### ISSUE TITLE
music isn't random

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#416]
I got several tracks in \lib\music\intro but everytime it playes the same track

also Serega reported that when he put this stuff for testing:
/music/town-day  amb_bell_metal1.mp3, amb_bell_metal2.mp3, amb_bell_tibet1.mp3 ... 
it plays in the same order

**Comment by s88100** [comment]
When I restart the client, music is not randomized and plays in the same order.
randomized after changing locations.

**Comment by draconisPW** [comment]
Maybe the client is "seeded" at that point (using the deterministic RNG), I'll try to see if using the "simple RNG" fixes the problem.

**Comment by draconisPW** [comment]
Reproduced. I have 5 tracks named 1-5 in both /intro and /town directories.
1) Intro music always plays 1
2) Intro music only plays music once
3) Town music always plays 5-4-5-1 in the same order

**Comment by draconisPW** [comment]
Problem 2 is solved. Now intro music always plays 1-5-4-5 in teh same order.

**Comment by draconisPW** [comment]
Ok it's a more general problem. The RNG is never initialized on the client, which means it always starts with a seed of 0 and uses the simple RNG. So first roll is seed 0, second roll is seed 12345, and so on... The problem is... on the client, the RNG is only used for two things: the randomization of sex/race/class during character creation... and now the choice of music to play. This means if you disable intro music and pick a random char, you'll always end up with a female Thunderlord Archer. Fix: "randomize" the RNG on the client by seeding it with something pertinent.

**Comment by draconisPW** [comment]
... or just call Rand_init() like on the server.

**Comment by draconisPW** [comment]
Fixed.
