### ISSUE TITLE
training dummy disappears

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#453]
- when you start fresh server - training dummy appear at once
- after some time pretty strange thing happens - periodically training dummy disappears
- Teleport Other doesn't (and shouldn't) work on it
- it doesn't spawn if you & -> 8 -> Advance time.. it spawns only if player was online there

How it can disappear?

**Comment by igroglaz** [comment]
Maybe it's because of monster's amount in town.. so when it become max, dummy doesn't get to the list sometimes?

```
name:Farfest
# TOWN
short:0_1
wpos:0:1
max-townies:100
#red tower
symbol:obj_grass2 e
```

**Comment by draconisPW** [comment]
Probably because your town.txt is incorrect:

"Base town should ALWAYS be the second entry in the list."
"Base town containing the main Angband dungeon"

Tangaria doesn't follow these rules.

Anyway, I removed the checks where you could move the dummy and simply prevented NO_DEATH from being moved at all, so the target dummy should never be able to move from its spot now.

**Comment by igroglaz** [comment]
"Tangaria doesn't follow these rules." it follows :) but base town is 1st location (ranger's tavern); and Farfest is not base town, but a regular town. So if dummy will be in 1st location - it will work alright.. I see, thanks! (though it's pointless to have dummy in 1st location, so thanks for removing checks!)
