### ISSUE TITLE
Fire-till-kill breaks casting/shooting

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#465]
```
[22:32] PowerWyrm: \e vs autoretaliator still doesn't work
[22:34] PowerWyrm: "the phantom warrior is targeted - the phantom warrior hits you - you dissolve the phantom warrior"
[22:34] PowerWyrm: "is targeted means the macro got registered and target was acquired but spell didn't happen, instead the turn was used for AR
[22:35] PowerWyrm: active AR is also doing nothing since AR is triggered anyway
```

....

`[15:48] PowerWyrm: I added a boolean for macros so it's set to true when macro arrives with first escape then to false when the "end macro" packet arrives and currently AR is disabled when the boolean is true (during macro), but I guess the "end macro" packet arrives before the AR check is made so it doesn't work (easy to check: you get message "enemy is targeted" when macro arrives, but then nothing happens and AR is triggered) -- I will have to rework it so the boolean is set at the end of the turn, but it's hard because you may use energy (easy case: AR is disabled until you get energy back), or not (macro that does nothing: the nAR would be disabled forever, which was he initial bug) `

**Comment by draconisPW** [comment]
Player turn, auto-retaliator enabled, no casting:
051021 115431 auto_retaliate: p->firing_request=0
051021 115431 PowerWyrm: You miss the wild cat.

Enemy turn:
051021 115431 PowerWyrm: The wild cat claws you (2).

Player turn, casting request, energy buildup:
051021 115432 PowerWyrm: The wild cat is targeted.
051021 115432 Receive_cast: p->firing_request=99
...
051021 115433 Receive_cast: p->firing_request=99

Enemy turn:
051021 115433 PowerWyrm: The wild cat claws you (3).

Player turn, casting request:
**051021 115433 Receive_cast: p->firing_request=0**
051021 115433 PowerWyrm: The wild cat is targeted.
051021 115433 Receive_cast: p->firing_request=99

The problem is here: being hit in melee resets the firing_request parameter, which cancels previous attempt to cast. At best, auto-retaliator kicks in, at worse the turn is lost and enemy gets free turns.

**Comment by draconisPW** [comment]
I think the fix is to set firing_request to 1 when canceling fire-till-kill instead of setting to 0.

**Comment by draconisPW** [comment]
This is a nasty bug. Since fire-till-kill was introduced, any disturbance cancels spells and archery. It was a bad idea to code firing_request the same way as digging_request (as a repetitive task). Fire-till-kill should be implemented simply as it is: continue until kill or disturbed. This should never impact manual casting/shooting. Therefore I'll revert firing_request as integer and change it as boolean, which is set on first call and reset if target is killed or action is disturbed.

**Comment by draconisPW** [comment]
Ok I HOPE it is FINALLY fixed!
