### ISSUE TITLE
STAR visual effects

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#489]
effect:STAR: got wrong visualization - one ray going to bottom instead of *

reproduce in PWMA:
create summoner and cast 
`spell:Thunderstorm:25:10:65:25:0` (3rd book)

**Comment by draconisPW** [comment]
There is a "did_visuals" parameter to optimize visual effects, I need to check if it's actually a bug or just optimization.

**Comment by igroglaz** [comment]
I've tested it in ASCII mode

**Comment by draconisPW** [comment]
In fact this is not a bug but is due to some optimization code (of the MAngband era, then ported to V): once a bolt or a blast is displayed, none other can be displayed in the same turn. This is to avoid client freezing in case the player does something stupid like getting in LoS of a whole hound pack or dragon pit and they all breathe at once, doing a million animations on screen at once. In this case, only one is displayed, since what's happening is obvious.

I'll add a parameter for STAR effect to allow breaking that rule when the player does it.
