### ISSUE TITLE
Trueart generation crush

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#494]
https://youtu.be/hT_W5SztxrA

maybe this issue connected with recent https://github.com/draconisPW/PWMAngband/issues/492 .. as it's the same character. so maybe previously trueart lamp was generated wrongly and messed character history somehow?.. Or maybe it's other issue.

**Comment by draconisPW** [comment]
Last time we fixed a garbled h->entries[107] and set it no NULL. This means I need to add some checks, because we do h->entries[i].art which assumes h->entries[i] is not NULL.

**Comment by draconisPW** [comment]
The video doesn't show why it crashes because we miss info. I thought at first it was because of NULL h->entries[i], but h->entries[i] is a structure and cannot be NULL, just empty. I think obj->artifact must be an invalid pointer, need to verify this.

**Comment by draconisPW** [comment]
This is a more severe problem. Currently, when saving an "artifact", we save first the artifact index art->aidx as a "byte" (0 to 255). We use aidx=255 to save the "known" part of the artifact (obj->artifact->known), which is mapped to :00000001. There are currently 236 artifacts in PWMAngband with 9 slots reserved for the Nazgul randart rings, meaning that 245 artifacts are saved in the server savefile. You see where this is going... If you add 10 more artifacts to artifact.txt, the 255th artifact will be saved with index 255... and loaded as :00000001 instead of the proper artifact structure! Since the game isn't prepared for this case, a crash occurs. Even worse, every other artifact after that will clash with the first artifacts in the list (index 256 will be saved as index 1 so when loading artifact 256 you'll get the info for artifact 1 instead).
Fix: save aidx as an integer and not a byte!
Note: this will break savefile compatibility, so cannot be applied without a wipe. I'll commit this fix along with latest V changes which also broke savefile compatibility in one go.

**Comment by draconisPW** [comment]
Same mistake also occurs for ego items, I'll fix that too.

**Comment by draconisPW** [comment]
Fixed. Now egos and artifacts indexes are saved as u16b which allows 65536 entries (should be more than enough).
