### ISSUE TITLE
Moving checks not fully applied when switching place

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#505]
demo (timecode): https://youtu.be/V48smVBJqAs?t=1606

player can swap place with minions to avoid traps

**Comment by draconisPW** [comment]
Lame bug.

**Comment by draconisPW** [comment]
Actually a LOT of "moving" code is not applied when "switching place" with either a player or a monster. This needs more work than expected and should be factorized.

**Comment by draconisPW** [comment]
In fact, since monsters don't care about being moved around, switching place with a monster is nothing more than moving the monster and then the player using the same code as if there was no monster, so it's pretty trivial to fix. Switching place with a player will be insanely difficult to fix, as using the same method would work for the player that moves but not for the player that is moved. And you cannot use the moving code here as it would infinitely recurse or would require an absolute insane amount of checks (for example: what to do if both players are standing on traps and one player fails to disarm a trap, but the other succeeds? what if a player is wraithed and stands on a wall?). For simplicity (and sanity) purposes, I will consider that the player that is moved gets no extra checks and therefore apply the same rule as if that player was a monster.

**Comment by igroglaz** [comment]
I suppose switching place with a player to avoid trap is not the case which we should worry about as to do so one player must already step into the trap which will trigger it.. so it's not really possible to cheeze this way - it's more like a feature, not a but. I think we can just fix the case with minions, thats it ;)

**Comment by draconisPW** [comment]
Fixed.

**Comment by draconisPW** [comment]
Note: to fix the player problem, I've simply prevented switching places if the starting square is not valid (aka: you're standing on a lava tile with immfire player and switch place with other player that is not immfire, that would kill that player -- now this cannot happen anymore).

**Comment by igroglaz** [comment]
timecode:
https://youtu.be/e9iKA0WjrT4?t=79

I appeared in tight spot with my bear.. he appeared on the trap and I wasn't able to swap with him

**Comment by draconisPW** [comment]
Yeah I'm a dumbass. Adding the extra checks before switching place triggers the disarm code, which checks if there is a monster over the trap... Will need to adjust this.

**Comment by draconisPW** [comment]
Unfortunately I cannot do this, since there are traps that alter terrain and swapping + triggering a trap won't work. In the end the above behavior is indeed correct: you cannot swap with someone if standing on a trap. In that case you will have to adapt.
