### ISSUE TITLE
paralyze status.. but player can move

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#518]
_[23:16] Кромвел: playing as a druid. In the form of a panther, the paralyzed effect grabbed me somewhere (probably there was a trap). A red inscription (status "Paralyzed") appeared at the bottom of the screen, but I continued to walk and even killed the mob._

server log:
```
120122 231422 Horgra: There is a wall in the way!
120122 231423 Alexantur IV: There is a wall in the way!
120122 231424 Horgra: There is a wall in the way!
120122 231424 MaDKnighT VI: You are surrounded by a strange white mist!
120122 231424 MaDKnighT VI: You are paralyzed! <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
120122 231425 Horgra: There is a wall in the way!
120122 231425 Alexantur IV: There is a wall in the way!
120122 231425 Alexantur IV: There is a wall in the way!
120122 231425 Alexantur IV: There is a wall in the way!
120122 231425 Alexantur IV: There is a wall in the way!
120122 231425 Alexantur IV: There is a wall in the way!
120122 231426 Alexantur IV: There is a wall in the way!
120122 231426 Alexantur IV: There is a wall in the way!
120122 231426 Alexantur IV: There is a wall in the way!
120122 231426 Alexantur IV: There is a wall in the way!
120122 231426 MaDKnighT VI: The fruit bat misses you.
120122 231426 MaDKnighT VI: The fruit bat misses you.
120122 231427 MaDKnighT VI: The fruit bat misses you.
120122 231427 Horgra: There is a wall in the way!
120122 231427 MaDKnighT VI: The fruit bat misses you.
120122 231427 Horgra: There is a wall in the way!
120122 231427 Horgra: There is a wall in the way!
120122 231427 MaDKnighT VI: The fruit bat misses you.
120122 231427 MaDKnighT VI: You punch the fruit bat (15).
120122 231427 MaDKnighT VI: You have slain the fruit bat.
120122 231428 Vontir II: There is a wall in the way!
120122 231428 MaDKnighT VI: There is a wall blocking your way.
120122 231430 MaDKnighT VI: You see a Scroll of Treasure Detection.
120122 231430 Horgra: You are drowning!
120122 231431 Horgra: You are drowning!
120122 231431 Vontir II: There is a tree in the way!
120122 231432 Horgra: There is a wall in the way!
120122 231432 Vontir II: There is a tree in the way!
120122 231432 Horgra: There is a wall in the way!
120122 231432 Horgra: You are drowning!
120122 231432 MaDKnighT VI: You can move again.  <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
120122 231432 MaDKnighT VI: You have a Scroll of Treasure Detection (j).
120122 231432 Horgra: You are drowning!
120122 231433 Horgra: You are drowning!
120122 231434 Horgra: You are drowning!
```

seems this trap:

```
name:gas trap:sleep gas trap
graphics:^:g
appear:1:2:0
visibility:20+d5
flags:TRAP | FLOOR
effect:TIMED_INC:PARALYZED
dice:5+1d10
desc:A trap that releases gas to put you to sleep.
msg:You are surrounded by a strange white mist!
```

**Comment by igroglaz** [comment]
T issue

**Comment by igroglaz** [comment]
Also interesting thing: if you are paralyzed and stay nearby to Training Dummy - you won't attack it automatically. But you will do it manually - if you 'move' towards it. So _maybe_ (suspicion) player can increase his number of attacks by moving towards enemy if he's got high value of additional MOVES. Eg in Tangaria player reported that he 'feels' that he can increase his DPS when he plays Half-Giant race (he's got now +17 move speed). Might be the other side of the coin of this bug (or a new one?).

**Comment by draconisPW** [comment]
The problem lies with how energy is spent while moving. It uses energy_per_move() which depends on num_moves instead of move_energy(), while paralyzation spends a turn using move_energy(). Since energy_per_move() uses less energy when num_moves is greater than 0, you can continue moving while paralyzed. Note: if you do anything else while paralyzed (for example: try to read a scroll), you will spend energy using move_energy() which will reset it and then paralyzation will prevent you from getting more, so the problem fixes itself.

Fix: simply by adding a check to prevent moving while paralyzed.

**Comment by draconisPW** [comment]
In fact this is even easier...

Looking at V code, which I ported, paralyzation is handled by: if (p->timed[TMD_PARALYZED]) do_cmd_sleep(p);
But in do_cmd_sleep(), V does: player->upkeep->energy_use = z_info->move_energy; (use energy).
And I ported this as: if (has_energy(p, true)) use_energy(p);

Basically V spends all the energy while I only spend energy if there is enough for a full turn. Of course moving with extra moves doesn't spend a full turn, so you can still do it.

This means some stupid coder didn't port V change properly...

**Comment by draconisPW** [comment]
To put it explicitely, PWMAng code continues to accumulate energy until player has enough for a full turn then checks for paralyzation and spends it if paralyzed so you can't do any action that requires a full turn. But all actions that require LESS than a turn (for example: fast casting, shooting with extra shots, walking with extra moves...) will still go through... that's why V code has to be applied and energy spent as soon as it is acquired when paralyzed.
