### ISSUE TITLE
identified ammo require ID before selling

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#528]
![1 (2)](https://user-images.githubusercontent.com/39904162/151165541-1dd2684c-5e37-450d-87b9-8d25b4ce2191.png)
![unknown](https://user-images.githubusercontent.com/39904162/151165553-ab9146eb-0a33-4a49-9f69-f126581f6980.png)

players shooting to enemies, but it doesn't help

**Comment by draconisPW** [comment]
object_all_modifiers_are_known() consider a modifier known only if known->modifier is non zero without checking that modifier is non zero. Items like basic missiles have no modifiers at all, and since they are never "wielded" (they go directly in teh quiver) their known modifier is never set. Everything else checks "if nonzero and known->zero it's unknown else it's known", so I'll change object_all_modifiers_are_known() to make the same check. I hope this doesn't break ID elsewhere...

**Comment by draconisPW** [comment]
Fixed.
