### ISSUE TITLE
ring goes to 'ignore' right away

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#552]
![image](https://user-images.githubusercontent.com/39904162/173181478-01dec5a2-7ada-4561-ab04-8b4817c8933e.png)

![image](https://user-images.githubusercontent.com/39904162/173181481-4c42a602-df7c-43d5-8126-7b8cc7342977.png)

I've met such behaviour too, plenty of times..

**Comment by draconisPW** [comment]
Item ignoring setup -> Quality ignoring options sets options by default to "worthless", meaning any worthless item is ignored by default, which is the case for rings of the mouse (due to -10 todam being worth more than the +2/+4 to stealth/dex, resulting in an item with a negative price rounded to zero).

Looking at V code, options are set to "no ignore" by default. I could revert the behavior like V, but since the options are saved in the savefile, they would be set to "no ignore" each time you start a new character. But I guess this isn't really a problem since there aren't that many worthless items anymore.

**Comment by draconisPW** [comment]
Reverted default ignoring options from "worthless" to "no ignore". From now on, you just select the object and use the ignore menu to ignore them without pre-defined setup for ignoring worthless stuff.
