### ISSUE TITLE
slay/brand/act flags for races/classes

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#6]
Add a possibility to use 'slay'/'brand'/'act' flags for race/class, like it's now for items, eg:
brand:ACID_3
slay:EVIL_2
act:DRAIN_LIFE

**Comment by draconisPW** [comment]
Wanna address this in this version to get rid of everything related to races/classes before starting to work on monsters. I'll add the slay/brand flags because it's easy. Activation is not a flag, so it would require too much work to add and won't be added. If by "act:DRAIN_LIFE" you mean "draining life like a vampire", I can simply add a VAMPIRIC brand like in TomeNET.

**Comment by igroglaz** [comment]
Great! 'Vampiric brand' would be great to have :)

**Comment by draconisPW** [comment]
Vampiric brand added in e69fc0d.

**Comment by draconisPW** [comment]
Innate race/class slays added in 9d1d406. This commit also fixes a bug with temporary slays (Smite Evil and Demon Bane spells), which would crash the server if used.
