### ISSUE TITLE
CHArisma stat

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#60]
_Make PWMA great again! Return CHArisma stat!_

But seriously. Having possibility to rebalance prices for which you buy consumables in shops - great deal which helps a lot in races rebalance.

Also CHA could be primary stats for some class spells (I heard a rumors that Necromancer and  Summoner in PWMA had it before); and not only - it could share % of 'spell failture' stat or certain % of mana amount for some other races (Priest, Paladin, Blackguard, Telepath?).

And... it could prevent seducing! :D

**Comment by draconisPW** [comment]
Charisma will never return, because it's too limited. But something else may...

**Comment by igroglaz** [comment]
Give us a sneak-peak :)

**Comment by draconisPW** [comment]
I will add a new stat called WILLPOWER! With a stronger will, you may influence how events turn.

- better prices in stores (because you're more confident -- this will replace the old Charisma effects)
- new stats for some classes, mainly Summoners (because you need a lot of will to maintain summons under control)
- better saving throws (because your mind is stronger, you will resist ailments like confuse, hold, blind... better)
- probably more!

**Comment by igroglaz** [comment]
Cool. But there is a problem to wrap willpower into the lore of the game. All powerful creatures like dragon, thunderlord, ent (and some tangaria races) - they've got loads of willpower according to 'make-sense' fantasy lore. 

So adding willpower will make already powerful races even more powerful and weak races even more weak. CHArisma is another story - as huge dragons, thunderlords or vampires lack of it - and it will be logical that common folk (NPC vendors) afraid of them and that's why give them high prices.

Another good thing about CHArisma - that it's classic DnD parameter https://roll20.net/compendium/dnd5e/Ability%20Scores#content . And in DnD wisdom+charisma is kinda 'willpower'
