### ISSUE TITLE
crush on breath

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#602]
https://www.youtube.com/watch?v=0AggKOZ7VDI

I suppose it may be connected with recent 'second chance' code: https://github.com/igroglaz/Tangaria/commit/ccd237a7417e8dc87e5c9db8e4a363068892e067#diff-c1ede660ea6b21ba87cf1610eb5c1b2a77b339c6e799b668d425a485444365ae
as last message in game's log is:
```
            msg(p, "Death nearly grasped you, but in the last moment....");
            msg(p, "........something pulled you into the aether........");
```

**Comment by igroglaz** [comment]
p is ok there:
![image](https://github.com/draconisPW/PWMAngband/assets/39904162/58e145e9-72bc-419b-9b69-cbd084e4cab5)

we compare it with origin (which contain memory garbage):
![image](https://github.com/draconisPW/PWMAngband/assets/39904162/bf391b70-a7bd-4d78-8a48-e20e7428ecbb)
... which is as it should be as it's monster attack.. p got his blow there:
![image](https://github.com/draconisPW/PWMAngband/assets/39904162/dffff603-4014-473e-b053-7fadabcbc0f8)

but when we process side effects there is no player in context:
![image](https://github.com/draconisPW/PWMAngband/assets/39904162/99e35f94-82b5-487f-bf97-2bf9cc2484f7)


so we send empty p
![image](https://github.com/draconisPW/PWMAngband/assets/39904162/460c5146-7695-412a-9f88-c45f37e582e0)

**Comment by igroglaz** [comment]
so monster tried to learn with update_smart_learn() from empty player

**Comment by draconisPW** [comment]
equip_learn_flag() requires a valid player pointer p, at 0:12 we can see on the left that p is NULL, that's why the game crashes.

From what I understand from the log, the player met a baby law drake that breathed shards, then player phased away out of sight of the drake which breathed sound. What I don't understand is why the player is "starving" and then "rises up through the ceiling"... that's clearly not what sound does.

**Comment by igroglaz** [comment]
"second life" thingy teleports player away ( https://github.com/igroglaz/Tangaria/commit/ccd237a7417e8dc87e5c9db8e4a363068892e067#diff-c1ede660ea6b21ba87cf1610eb5c1b2a77b339c6e799b668d425a485444365ae ).... I suppose it bad idea.. should be post-pone teleport somehow?
            source_player(who, get_player_index(get_connection(p->conn)), p);
            effect_simple(EF_TELEPORT_LEVEL, who, "0", 0, 0, 0, 0, 0, NULL);

**Comment by draconisPW** [comment]
The problem is that "sound breath" must have been modified somewhere to include "hunger" and then "teleport level" which should never happen, effects should not be modified without adapting the code. The sound routine expects the player to be on the same spot which is not the case if the effect also teleports the player out of the level.

**Comment by draconisPW** [comment]
Fix: adapt your "second chance code" to be coded into the "death" routine. There is already code there (blackguard + necromancer can already avoid death) you can take example.
