### ISSUE TITLE
ironman towns on regular server

### ISSUE THREAD

**Issue by igroglaz** [draconisPW/PWMAngband#619]
if you run the regular server and player will choose to player Ironman (`no_recall+force_descend` player options) - they will appear in Carn Dum. Problem is - there are no towns there

`[21:28]PowerWyrm: so the option is in dungeon.txt for example flag:IRONMAN`
/rfe to add generation of 1000 2000 3000 4000 towns for no_recall + force_descend on regular (non-ironman server)

**Comment by igroglaz** [comment]
it will be fun to call it like STATIC_TOWN (as "IRONMAN" name better to use for other flag)

**Comment by draconisPW** [comment]
The current behavior is correct since birth_no_recall mimics V ironman mode: you start from the V town, go down the stairs and try to go kill Morgoth without ever visiting the town again. To activate MAngband ironman mode (towns every 20 levels), the server option DIVING_MODE needs to be set instead.

The idea would be to generate dungeons which would have the towns every 20 levels and would be available to any player via a flag in dungeon.txt. This would mimic the MORE_TOWNS server option.

**Comment by draconisPW** [comment]
Implemented in commit 6612105. To get the static towns in your ironman dungeon, just add MORE_TOWNS in the "flags" line of your dungeon.
